spring.application.name=designation.gen

spring.datasource.url=jdbc:sqlite:coelho-manager.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

IMAGES_REPOSITORY_PATH=${IMAGES_REPOSITORY_PATH:{CAMINHO_REPOSITORIO_IMAGENS}}
TESSDATA_PATH=${TESSDATA_PATH:{CAMINHO_TESSDATA_OCR}}
TRAFFIC_IMAGE_ISP_PATH=${TRAFFIC_IMAGE_ISP_PATH:src/main/resources/templates/isp-client-form/images/traffic.png}

netbox.url=${NETBOX_URL:{NETBOX_URL}}
netbox.token=${NETBOX_TOKEN:{NETBOX_TOKEN}}

mail.from=${MAIL_FROM:{EMAIL_REMETENTE}}
mail.report.template=${MAIL_REPORT_TEMPLATE:templates/mail-report-template.txt}
mail.sender.template=${MAIL_SENDER_TEMPLATE:templates/mail-sender-template.txt}
mail.to.default.path=${MAIL_TO_DEFAULT_PATH:templates/isp-client-form/default-mails.txt}

spring.mail.host=${SMTP_HOST:{SMTP_HOST}}
spring.mail.port=${SMTP_PORT:587}
spring.mail.username=${SMTP_USER:{SMTP_USER}}
spring.mail.password=${SMTP_PASSWORD:{SMTP_PASSWORD}}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

